version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "3001:443"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro