name: Sync to Another Repository

on:
  push:
    branches:
      - main  # 감시할 브랜치를 지정합니다.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: 대상 리포지토리로 푸시
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "tripleyoung  "
          git config --global user.email "dudnjsckrgo@gmail.com"
          git remote add target https://tripleyoung:${{ secrets.PAT_TOKEN }}@github.com/tripleyoung/master-of-prediction-frontend.git
          git push target main
